### ISSUE TITLE
Big replicator bug

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [realmayus/YouMatter#39] opened 2020-02-23 04:31 UTC
mc 1.15.2
forge-1.15.2-31.1.14
youmatter-1.15.2-1.9
refinedstorage-1.8.1

If you automatically extract the items from REPLICATOR 
you get everything from the PREVIEW section, instead from the output.
that means, the items dont have to be created, just selected using
green arrows. 
1 tick=1 item, no u-matter used.
the IMPORTER from refined storage is able to import everything, 
thumb, preview, tank, output.
just set the blacklist-filter and you never eed u-mater again.

 regards

**Comment by realmayus** [comment] 2020-02-23 12:10
Cannot reproduce using mekanism pipes, now trying refinedstorage importers

**Comment by realmayus** [comment] 2020-02-23 12:15
CAN reproduce

**Comment by realmayus** [comment] 2020-02-23 12:29
Should also happen in 1.14.4 but not in 1.12.2

**Comment by realmayus** [comment] 2020-02-23 12:53
Thanks for reporting, this is fixed in Beta 2.0 (https://www.curseforge.com/minecraft/mc-mods/youmatter/files/all)

**Closed as completed by realmayus** 2020-02-23 12:53 UTC
Labels: Bug, Urgent, 1.14.X, 1.15.X
